INSERT INTO `auth_controller_ignore` (`controller`, `action`) VALUES
('Index', 'main'),
('Core', 'call'),
('User', 'checkLogin'),
('User', 'login'),
('User', 'logined'),
('Vericode', 'check'),
('Vericode', 'simple');
INSERT INTO `character` (`id`, `name`) VALUES
(1, '系统管理员');
INSERT INTO `auth_character_controller` (`character_id`, `controller`, `action`) VALUES
(1, 'Admin', 'auth'),
(1, 'Admin', 'character'),
(1, 'Admin', 'main'),
(1, 'Admin', 'user'),
(1, 'Admin', 'usergroup'),
(1, 'Auth', 'addCAIgnore'),
(1, 'Auth', 'addCharacterCA'),
(1, 'Auth', 'delCAIgnore'),
(1, 'Auth', 'delCharacterCA'),
(1, 'Auth', 'listCA'),
(1, 'Auth', 'listCharacterCA'),
(1, 'Auth', 'main'),
(1, 'Index', 'main'),
(1, 'User', 'addCharacter'),
(1, 'User', 'addGroup'),
(1, 'User', 'addGroupCharacter'),
(1, 'User', 'addUser'),
(1, 'User', 'addUserCharacter'),
(1, 'User', 'banUser'),
(1, 'User', 'checkLogin'),
(1, 'User', 'delCharacter'),
(1, 'User', 'delGroupCharacter'),
(1, 'User', 'delUserCharacter'),
(1, 'User', 'editUser'),
(1, 'User', 'groupList'),
(1, 'User', 'listCharacter'),
(1, 'User', 'listGroupCharacter'),
(1, 'User', 'listUserCharacter'),
(1, 'User', 'login'),
(1, 'User', 'logined'),
(1, 'User', 'logout'),
(1, 'User', 'moveGroup'),
(1, 'User', 'moveUser'),
(1, 'User', 'removeGroup'),
(1, 'User', 'removeUser'),
(1, 'User', 'renameCharacter'),
(1, 'User', 'renameGroup'),
(1, 'User', 'searchList'),
(1, 'User', 'setGroupCharacter'),
(1, 'User', 'userList'),
(1, 'Vericode', 'check'),
(1, 'Vericode', 'simple');
